#!/usr/bin/env python3
"""Dependency-free, fail-closed PGN and FEN import for local review.

Only the main line is imported.  Every SAN token is matched against moves
generated by :mod:`san`, so comments, variations, or malformed notation can
never silently create an authoritative position.
"""

import re
from pathlib import Path

import san


STANDARD_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
MAX_FILE_BYTES = 2 * 1024 * 1024
MAX_PLIES = 2048
MAX_HEADERS = 64
MAX_HEADER_VALUE = 1024
RESULTS = {"1-0", "0-1", "1/2-1/2", "*"}

TAG_RE = re.compile(
    r'^\s*\[([A-Za-z][A-Za-z0-9_]*)\s+"((?:\\.|[^"\\])*)"\]\s*$'
)
MOVE_NUMBER_RE = re.compile(r"^\d+\.(?:\.\.)?")
NAG_RE = re.compile(r"\$\d+")
SUFFIX_RE = re.compile(r"[+#!?]+$")
UCI_RE = re.compile(r"^[a-h][1-8][a-h][1-8][qrbn]?$", re.IGNORECASE)

FIGURINES = str.maketrans({
    "♔": "K", "♕": "Q", "♖": "R", "♗": "B", "♘": "N",
    "♚": "K", "♛": "Q", "♜": "R", "♝": "B", "♞": "N",
})


class ImportError(ValueError):
    """A user-facing import error, distinct from filesystem failures."""


def canonical_fen(raw_fen):
    """Validate and return an exact, canonical six-field FEN."""
    if not isinstance(raw_fen, str):
        raise ImportError("FEN must be text")
    fields = raw_fen.strip().split()
    if len(fields) != 6:
        raise ImportError("FEN needs all six fields")

    placement, side, rights, target, halfmove, fullmove = fields
    rows = placement.split("/")
    if len(rows) != 8:
        raise ImportError("FEN board needs eight ranks")
    pieces = []
    for row in rows:
        count = 0
        previous_digit = False
        for character in row:
            if character in "12345678":
                if previous_digit:
                    raise ImportError("FEN ranks may not contain adjacent digits")
                count += int(character)
                previous_digit = True
            elif character in "prnbqkPRNBQK":
                count += 1
                pieces.append(character)
                previous_digit = False
            else:
                raise ImportError("FEN contains an unknown board character")
        if count != 8:
            raise ImportError("Every FEN rank must contain eight squares")
    if pieces.count("K") != 1 or pieces.count("k") != 1:
        raise ImportError("FEN needs exactly one king of each colour")
    if side not in {"w", "b"}:
        raise ImportError("FEN side to move must be 'w' or 'b'")
    if rights != "-":
        canonical_rights = "".join(value for value in "KQkq" if value in rights)
        if canonical_rights != rights or len(set(rights)) != len(rights):
            raise ImportError("FEN castling rights must be '-' or canonical KQkq")
    if target != "-" and not re.fullmatch(r"[a-h][36]", target):
        raise ImportError("FEN en-passant target must be '-' or a square on rank 3 or 6")
    try:
        halfmove_value = int(halfmove)
        fullmove_value = int(fullmove)
    except ValueError as error:
        raise ImportError("FEN move counters must be whole numbers") from error
    if halfmove_value < 0 or fullmove_value < 1:
        raise ImportError("FEN move counters are outside their valid range")

    text = " ".join((placement, side, rights, target, str(halfmove_value), str(fullmove_value)))
    try:
        board = san.Board(text)
    except ValueError as error:
        raise ImportError(f"Invalid FEN: {error}") from error

    if board.squares.count("P") > 8 or board.squares.count("p") > 8:
        raise ImportError("FEN contains too many pawns")
    if any(piece.lower() == "p" for piece in board.squares[:8] + board.squares[56:]):
        raise ImportError("FEN pawns cannot stand on the first or eighth rank")
    white_king = board.king_square(True)
    black_king = board.king_square(False)
    if white_king is None or black_king is None:
        raise ImportError("FEN needs exactly one king of each colour")
    white_row, white_file = divmod(white_king, 8)
    black_row, black_file = divmod(black_king, 8)
    if max(abs(white_row - black_row), abs(white_file - black_file)) <= 1:
        raise ImportError("FEN kings may not touch")
    if board.in_check(not board.white_to_move):
        raise ImportError("FEN leaves the side that just moved in check")

    required_home = {
        "K": ((60, "K"), (63, "R")),
        "Q": ((60, "K"), (56, "R")),
        "k": ((4, "k"), (7, "r")),
        "q": ((4, "k"), (0, "r")),
    }
    for right in board.castling:
        if any(board.squares[index] != piece for index, piece in required_home[right]):
            raise ImportError(f"FEN castling right {right} has no king and rook at home")
    if board.en_passant is not None:
        expected_rank = "6" if board.white_to_move else "3"
        target_name = san.square_name(board.en_passant)
        pawn_index = board.en_passant + (8 if board.white_to_move else -8)
        origin_index = board.en_passant + (-8 if board.white_to_move else 8)
        expected_pawn = "p" if board.white_to_move else "P"
        if (
            target_name[1] != expected_rank
            or board.squares[board.en_passant] != "."
            or board.squares[pawn_index] != expected_pawn
            or board.squares[origin_index] != "."
        ):
            raise ImportError("FEN en-passant target does not match the last pawn move")
    return board.fen()


def _unescape_header(value):
    output = []
    escaped = False
    for character in value:
        if escaped:
            output.append(character)
            escaped = False
        elif character == "\\":
            escaped = True
        else:
            output.append(character)
    if escaped:
        output.append("\\")
    return "".join(output)


def _split_headers(text):
    headers = {}
    body = []
    in_headers = True
    saw_header = False
    for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        stripped = line.strip()
        if in_headers and (not stripped or stripped.startswith("[")):
            if not stripped:
                if saw_header:
                    in_headers = False
                continue
            match = TAG_RE.fullmatch(line)
            if match is None:
                raise ImportError(f"Malformed PGN header: {stripped[:80]}")
            if len(headers) >= MAX_HEADERS:
                raise ImportError("PGN contains too many headers")
            key, raw_value = match.groups()
            value = _unescape_header(raw_value)
            if len(value) > MAX_HEADER_VALUE:
                raise ImportError(f"PGN header {key} is too long")
            headers[key] = value
            saw_header = True
            continue
        in_headers = False
        body.append(line)
    return headers, "\n".join(body)


def _mainline_text(text):
    output = []
    variation_depth = 0
    in_brace = False
    in_semicolon = False
    for character in text:
        if in_semicolon:
            if character == "\n":
                in_semicolon = False
                if variation_depth == 0:
                    output.append(" ")
            continue
        if in_brace:
            if character == "}":
                in_brace = False
            continue
        if character == "{":
            in_brace = True
            continue
        if character == ";":
            in_semicolon = True
            continue
        if character == "(":
            variation_depth += 1
            continue
        if character == ")":
            if variation_depth == 0:
                raise ImportError("PGN contains an unmatched variation close")
            variation_depth -= 1
            continue
        if variation_depth == 0:
            output.append(character)
    if in_brace:
        raise ImportError("PGN contains an unterminated comment")
    if variation_depth:
        raise ImportError("PGN contains an unterminated variation")
    return "".join(output)


def _san_key(token):
    value = token.translate(FIGURINES).strip()
    value = value.replace("\u00a0", "")
    value = re.sub(r"(?i)e\.?p\.?$", "", value).strip()
    value = SUFFIX_RE.sub("", value)
    value = value.replace("0-0-0", "O-O-O").replace("0-0", "O-O")
    value = value.replace("=", "")
    if value and value[0] in "kqrbn":
        value = value[0].upper() + value[1:]
    if len(value) >= 3 and value[-1] in "qrbnQRBN" and value[-2] in "18":
        value = value[:-1] + value[-1].upper()
    return value


def _tokens(body):
    cleaned = NAG_RE.sub(" ", _mainline_text(body))
    output = []
    for raw in cleaned.split():
        token = raw.strip()
        while True:
            reduced = MOVE_NUMBER_RE.sub("", token, count=1)
            if reduced == token:
                break
            token = reduced
        token = token.lstrip(".")
        if token.lower() in {"e.p.", "e.p", "ep"}:
            continue
        if token:
            output.append(token)
    return output


def _match_move(board, token, ply):
    legal = board.legal_moves()
    legal_uci = [
        san.square_name(origin) + san.square_name(target) + promotion
        for origin, target, promotion in legal
    ]
    if UCI_RE.fullmatch(token):
        candidate = token.lower()
        if candidate in legal_uci:
            return candidate
    wanted = _san_key(token)
    matches = [
        move for move in legal_uci
        if _san_key(board.san(move, legal)) == wanted
    ]
    if len(matches) == 1:
        return matches[0]
    move_number = (ply + 1) // 2
    prefix = f"{move_number}." if ply % 2 else f"{move_number}..."
    if not matches:
        raise ImportError(f"Illegal or unsupported move at {prefix}: {token}")
    raise ImportError(f"Ambiguous move at {prefix}: {token}")


def _label(headers, fallback, result):
    white = headers.get("White", "").strip()
    black = headers.get("Black", "").strip()
    if white or black:
        players = f"{white or '?'} – {black or '?'}"
        return f"{players} · {result}"
    event = headers.get("Event", "").strip()
    if event and event != "?":
        return event
    return fallback or "Imported PGN"


def parse_pgn(text, source_name="Imported PGN"):
    """Parse one PGN main line and return a canonical local-review record."""
    if not isinstance(text, str):
        raise ImportError("PGN must be text")
    if len(text.encode("utf-8")) > MAX_FILE_BYTES:
        raise ImportError("PGN is larger than the 2 MB import limit")

    headers, body = _split_headers(text.lstrip("\ufeff"))
    mainline = _mainline_text(body)
    if re.search(r"(?m)^\s*\[[A-Za-z]", mainline):
        raise ImportError("Import one PGN game at a time")

    setup = headers.get("SetUp", "0").strip()
    fen_header = headers.get("FEN", "").strip()
    if setup == "1" and not fen_header:
        raise ImportError("PGN SetUp is 1 but no FEN header is present")
    if setup not in {"0", "1", ""}:
        raise ImportError("PGN SetUp header must be 0 or 1")
    initial_fen = canonical_fen(fen_header) if fen_header else STANDARD_FEN

    header_result = headers.get("Result", "*").strip() or "*"
    if header_result not in RESULTS:
        raise ImportError("PGN Result header is invalid")
    seen_result = None
    board = san.Board(initial_fen)
    moves = []
    for token in _tokens(mainline):
        if token in RESULTS:
            if seen_result is not None:
                raise ImportError("PGN contains more than one result marker")
            seen_result = token
            continue
        if seen_result is not None:
            raise ImportError("PGN contains moves after its result marker")
        if len(moves) >= MAX_PLIES:
            raise ImportError(f"PGN exceeds the {MAX_PLIES}-ply import limit")
        move = _match_move(board, token, len(moves) + 1)
        moves.append(move)
        board = board.apply_uci(move)

    result = seen_result or header_result
    if seen_result and header_result != "*" and seen_result != header_result:
        raise ImportError("PGN header and movetext results disagree")
    metadata = {
        key: value for key, value in headers.items()
        if key not in {"FEN", "SetUp"} and value
    }
    return {
        "initial_fen": initial_fen,
        "moves": moves,
        "uci_moves": "|".join(moves),
        "result": result,
        "metadata": metadata,
        "label": _label(headers, source_name, result),
        "final_fen": board.fen(),
    }


def parse_pgn_file(path):
    source = Path(path)
    try:
        size = source.stat().st_size
    except OSError:
        raise
    if size > MAX_FILE_BYTES:
        raise ImportError("PGN is larger than the 2 MB import limit")
    raw = source.read_bytes()
    try:
        text = raw.decode("utf-8-sig")
    except UnicodeDecodeError:
        # Traditional PGN archives commonly use ISO-8859-1. It is a
        # single-byte encoding, so this fallback is deterministic and cannot
        # hide truncated UTF-8 structural bytes.
        text = raw.decode("iso-8859-1")
    return parse_pgn(text, source.stem or "Imported PGN")
